management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: spring-boot-admin-server
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            client:
                username: ${spring.security.user.name}
                password: ${spring.security.user.password}
                url: http://localhost:8080
                instance:
                    metadata:
                        user:
                            name: ${spring.security.user.name}
                            password: ${spring.security.user.password}
